version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/roosh
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Vreenubmong4
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_AUTOCOMMIT=false
      - SERVER_PORT=8080
      - JWT_SECRET=31bef8636c930b9b3eb1b95c3184bf2dfee01f7ccfb0b38d1f36973d58ead4cf

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vreenubmong4
      MYSQL_DATABASE: roosh
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 5s
      interval: 10s

volumes:
  db-data:
