variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

sonarqube_analysis:
  stage: sonarqube
  script:
    - ./gradlew compileJava
    - ./gradlew clean test jacocoTestReport sonar
  only:
    - main